# Generated by Django 5.1.5 on 2025-01-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField()),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('sqft', models.DecimalField(decimal_places=3, max_digits=10)),
                ('year_built', models.PositiveIntegerField()),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('parking_spaces', models.PositiveIntegerField(default=0)),
                ('has_garage', models.BooleanField(default=False)),
                ('has_pool', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Real Estate Property',
                'verbose_name_plural': 'Real Estate Properties',
            },
        ),
    ]
