# Generated by Django 5.1.5 on 2025-01-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_state', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realstate',
            name='bathrooms',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='bedrooms',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='country',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='has_garage',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='has_pool',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='price',
            field=models.PositiveBigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='property_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], db_index=True, default='residential', max_length=50),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='year_built',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='realstate',
            index=models.Index(fields=['price'], name='real_state__price_5c69bf_idx'),
        ),
        migrations.AddIndex(
            model_name='realstate',
            index=models.Index(fields=['year_built'], name='real_state__year_bu_bf7514_idx'),
        ),
        migrations.AddIndex(
            model_name='realstate',
            index=models.Index(fields=['city', 'country'], name='real_state__city_37ea58_idx'),
        ),
    ]
