# Generated by Django 5.1.5 on 2025-01-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_state', '0002_alter_realstate_bathrooms_alter_realstate_bedrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realstate',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='realstate',
            name='sqft',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
    ]
